[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = 'max-age=31536000'
    X-Content-Type-Options = 'nosniff'
